version: "3.8"

services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/YagnikThanki/backend_api:latest
    image: ghcr.io/YagnikThanki/backend_api:latest
    command: gunicorn account.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/code/static
      - media:/usr/src/code/media

    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  static:
  media:
