name: Run tests
on: push
jobs:
  build:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update

      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.x"
      # - name: Install pip
      #   run: sudo apt install python3-pip
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pwd
      #     ls
      #     pip install -r requirements.txt
      - name: Generate ENV
        run: |
          chmod +x ./setup_env.sh
          bash ./setup_env.sh

      - name: before Script installation
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

        # run: |
        #   export

      - name: Docker Build & Image Push
        run: |
          export BACKEND_IMAGE='ghcr.io/virajamenity/backend_api:latest'
          export NGINX_IMAGE='ngnix'
          export IMAGE='test'

          docker images ls
          docker-compose -f docker-compose.yml build
          docker login ghcr.io -u virajamenity -p ${{ secrets.TOKEN_GITHUB }}
          docker push ghcr.io/virajamenity/backend_api:latest
